### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by keyurshah** [verbb/postie#22]
### Description
when installing via console 

`composer require verbb/postie`

i get the error

```
Using version ^2.1 for verbb/postie
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - verbb/base 1.0.0 requires craftcms/cms ^3.4.0-RC1 -> satisfiable by craftcms/cms[3.4.0-RC1, 3.4.0-RC1.1, 3.4.0-RC2, 3.4.0-RC3, 3.4.x-dev] but these conflict with your requirements or minimum-stability.
    - verbb/postie 2.1.0 requires verdant/xml2array dev-master -> satisfiable by verdant/xml2array[dev-master] but these conflict with your requirements or minimum-stability.
    - verbb/postie 2.1.1 requires verbb/base ^1.0.0 -> satisfiable by verbb/base[1.0.0].
    - Installation request for verbb/postie ^2.1 -> satisfiable by verbb/postie[2.1.0, 2.1.1].


Installation failed, reverting ./composer.json to its original content.
```

### Steps to reproduce

1. install via console using command `composer require verbb/postie`

### Additional info

- Plugin version: 2.1
- Craft version: 3.3.19
- Craft Commerce version: 2.2.14

Thanks

**Comment by engram-design** [comment]
Should be fixed in [2.1.1](https://github.com/verbb/postie/releases/tag/2.1.1)

**Comment by keyurshah** [comment]
I think verbb/base needs to be tagged with latest commit. I see the tag number , ‘1.0.0’ shows the code before the minimum version was lowered

**Comment by engram-design** [comment]
Totally right, that's been updated now. That would've only been half the problem, I was having issues with `verdant/xml2array` as well, so ended up removing it, as it was causing these sorts of issues

**Comment by keyurshah** [comment]
thanks for your help.

unfortunately i'm still getting an error as postie seems to want to use `verbb/base[1.0.0]` instead of `1.0.1` for some reason. this is the error i get:

```
  Problem 1
    - verbb/base 1.0.0 requires craftcms/cms ^3.4.0-RC1 -> satisfiable by craftcms/cms[3.4.0-RC1, 3.4.0-RC1.1, 3.4.0-RC2, 3.4.0-RC3, 3.4.x-dev] but these conflict with your requirements or minimum-stability.
    - verbb/postie 2.1.1 requires verbb/base ^1.0.0 -> satisfiable by verbb/base[1.0.0].
    - Installation request for verbb/postie ^2.1.1 -> satisfiable by verbb/postie[2.1.1].
```

in looking it up, it seems that updating a tag without a commit may not update packagist

https://github.com/composer/packagist/issues/587

**Comment by engram-design** [comment]
Yep, sorry about that. I actually though I'd fixed this all in 1.0.0 at the time, but I'd missed bundling the important commit. 1.0.1 should be working now.
